# permissions for end users to view nodelabelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nodelabeler
    app.kubernetes.io/managed-by: kustomize
  name: nodelabeler-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - nodelabelers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - nodelabelers/status
  verbs:
  - get
