---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.my.domain
  resources:
  - nodelabelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - nodelabelers/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.my.domain
  resources:
  - nodelabelers/status
  verbs:
  - get
  - patch
  - update
